### ISSUE TITLE
read more

### ISSUE THREAD

**Issue by deadcodeca** [eurialo/deftcode.ninja#2]
something seems to be up with the read more button, if the first post on the page has the  tag, it doesnt show anything else below that.

**Comment by eurialo** [comment]
Hi @deadcodeca! the **r34dm0r3** comment is used to split the first homepage post for applying the readmore button, as you can see in the _index.html_:

`{% if site.posts[0].content contains "r34dm0r3" %}
	{{ site.posts[0].content | split:"r34dm0r3" | first }}
{% else %}
	{{ site.posts[0].content }}
{% endif %}`

If the post contains the **r34dm0r3** comment the first part of post will be splitted and rendered before listing the others post.

**NOTE:** Apply the **r34dm0r3** comment only in the latest post you'll publish and remove from the older.
